InformedSolutions/JAQU-CAZ-Vehicle-Compliance-Checker-Web

.github/PULL_REQUEST_TEMPLATE
app/controllers/air_zones_controller.rb
app/controllers/application_controller.rb
app/controllers/vehicle_checkers_controller.rb

[JIRA](https://eaflood.atlassian.net/browse/VCCS-763)
Fix bug

[VCCS-763] Clear checked la's if no la was selected

---

app/views/air_zones/caz_selection.html.haml
app/views/air_zones/compliance.html.haml

[JIRA](https://eaflood.atlassian.net/browse/VCCS-773)
Home page:
CAZ selection:
Compliance page:

[VCCS-773] Revert update content

---

.drone.yml
jmeter/assertion.yml

changed jmeter assertion

---

jmeter/manual-load-test/gtd.rb
jmeter/manual-load-test/vccs-ve-concurrency-test.jmx
lib/rubocop/blacklist.yml

manual load tests, not to be run as part of build. GTD is added for test data generation.  The load test has two scenario - vehicle entrant request with 10 dynamic vrns and vccs ui with 1 dynamic vrn. Both use csv data configs.

[CI SKIP] manual tests

---

.drone.yml
app/views/air_zones/compliance.html.haml

Remove dead Find new ways to make your journey link

Remove dead link

---

app/views/vehicle_checkers/cannot_determinate.html.haml

[JIRA](https://eaflood.atlassian.net/browse/CAZ-1443)

[CAZ-1443] Fix back button exempt page

---

app/controllers/application_controller.rb

[NT] Skip basic auth for build_id and health

---

app/controllers/contact_forms_controller.rb
app/models/contact_form.rb
app/services/sqs/base_message.rb
app/views/contact_forms/form_input/_errored.html.haml
app/views/contact_forms/form_input/_normal.html.haml
config/initializers/content_security_policy.rb
features/contact_form.feature
features/step_definitions/contact_form_steps.rb
spec/models/contact_form_spec.rb
spec/requests/contact_forms_spec.rb
spec/services/sqs/jaqu_message_spec.rb
spec/services/sqs/user_message_spec.rb
spec/support/shared_examples/sqs_email.rb

[JIRA](https://eaflood.atlassian.net/browse/VCCS-806)

[VCCS-806] Update contact form

---

app/controllers/contact_forms_controller.rb
app/models/contact_form.rb
app/services/sqs/base_message.rb
app/views/contact_forms/form_input/_errored.html.haml
app/views/contact_forms/form_input/_normal.html.haml
config/initializers/content_security_policy.rb
features/contact_form.feature
features/step_definitions/contact_form_steps.rb
spec/models/contact_form_spec.rb
spec/requests/contact_forms_spec.rb
spec/services/sqs/jaqu_message_spec.rb
spec/services/sqs/user_message_spec.rb
spec/support/shared_examples/sqs_email.rb

Update release with contact form enhancements.

[VCCS-806] Update contact form (#231)

---

app/views/air_zones/caz_selection.html.haml
app/views/contact_forms/index.html.haml

[JIRA](https://eaflood.atlassian.net/browse/CAZ-1498)

Add hidden legend to contact form

---

app/controllers/privacy_notice_controller.rb
app/views/layouts/_footer.html.haml
app/views/privacy_notice/index.html.haml
config/routes.rb
features/privacy_notice.feature
features/step_definitions/privacy_notice_steps.rb
spec/requests/privacy_notice_spec.rb

[JIRA](https://eaflood.atlassian.net/browse/VCCS-815)

[VCCS-815] Add privacy notice page

---

app/views/welcome/index.html.haml
features/welcome.feature

[JIRA](https://eaflood.atlassian.net/browse/VCCS-874)

[VCCS-874] Update content

---

app/views/privacy_notice/index.html.haml

[JIRA](https://eaflood.atlassian.net/browse/VCCS-815)

[VCCS-815] Update privacy notice page

---

app/views/common/_external_link.haml
app/views/privacy_notice/index.html.haml
config/locales/en.yml

[JIRA](https://eaflood.atlassian.net/browse/VCCS-815)

[VCCS-815] Add visually hidden text to external links

---

app/services/sqs/user_message.rb
spec/services/sqs/user_message_spec.rb

[VCCS-862] Add name to Sqs::UserMessage

---

app/views/air_zones/compliance.html.haml
features/vehicle_checker.feature

[JIRA](https://eaflood.atlassian.net/browse/VCCS-857)
1.
2.

[VCCS-857] Add health warning on compliance page

---

app/javascript/src/printLink/init.js
app/javascript/src/printLink/styles.scss
app/views/air_zones/compliance.html.haml
app/views/common/_print_page.haml

https://eaflood.atlassian.net/browse/VCCS-895

[VCCS-895] Fix print link

---

app/javascript/src/printLink/init.js
app/javascript/src/printLink/styles.scss
app/views/air_zones/compliance.html.haml
app/views/common/_print_page.haml

Merge print link fix to v1.0.0 prior to deployment

Merge print link fix to v1.0.0 prior to deployment

---

app/views/contact_forms/index.html.haml
features/contact_form.feature

[NT] Use `There is a problem` error message on contact form

---

config/environments/production.rb

https://chriszetter.com/blog/2013/10/04/setting-headers-in-rails-4/

[NT] Add IE Edge header

---

app/views/welcome/index.html.haml

[NT] Fix home page content

---

.drone.yml
app/models/caz_form.rb
app/views/air_zones/caz_selection.html.haml
app/views/vehicle_checkers/country_input/_errored.html.haml
config/locales/en.yml
features/vehicle_checker.feature
spec/support/shared_examples/invalid_country_input.rb

[JIRA](https://eaflood.atlassian.net/browse/CAZB-78)

[CAZB-78] Update error messages

---

.drone.yml
Dockerfile.build
Dockerfile.test

Test ruby versioning updates with dockerfile edits

---

zap.conf

Promote dev updates for telephone number to SIT

Promote dev updates to SIT

---

Gemfile.lock
app/helpers/application_helper.rb
app/views/air_zones/caz_selection.html.haml
app/views/air_zones/compliance.html.haml
app/views/common/_external_link.haml
app/views/cookies/_ga.html.haml
app/views/cookies/index.html.haml
app/views/layouts/_feedback_section.html.haml
app/views/privacy_notice/index.html.haml
app/views/vehicle_checkers/cannot_determinate.html.haml
app/views/vehicle_checkers/incorrect_details.html.haml
app/views/vehicle_checkers/non_uk.html.haml
app/views/vehicle_checkers/number_not_found.html.haml
app/views/welcome/index.html.haml
features/air_zones.feature
features/vehicle_checker.feature
yarn.lock

CAZB-290, 292, 295, 296, 301 - Update content

[CAZB-290, 292, 295, 296, 301] Update content

---

.rubocop.yml
app/controllers/accessibility_controller.rb
app/views/accessibility/index.html.haml
app/views/layouts/_footer.html.haml
config/routes.rb
features/accessibility.feature
features/cookies.feature
features/privacy_notice.feature
features/step_definitions/cookies_steps.rb
features/step_definitions/helper_steps.rb
features/step_definitions/privacy_notice_steps.rb
spec/requests/accessibility_spec.rb

[JIRA](https://eaflood.atlassian.net/browse/CAZB-293)

[CAZB-293] Add accessibility statement page

---

app/controllers/contact_forms_controller.rb

[NT] Refactor determinate_back_path method in contact forms controller

---

app/views/accessibility/index.html.haml

[JIRA](https://eaflood.atlassian.net/browse/CAZB-293)

[CAZB-293] Update accessibility statement page

---

app/models/compliance.rb
app/models/compliance_details.rb
app/views/air_zones/compliance.html.haml
spec/models/compliance_details_spec.rb

[JIRA](https://eaflood.atlassian.net/browse/CAZB-88)

[CAZB-88] Update compliance page

---

.drone.yml
package.json
yarn.lock

[NT] Use yarn exclude 961 unless fix will be released

---

app/api_wrapper/compliance_checker_api.rb
app/controllers/air_zones_controller.rb
app/controllers/application_controller.rb
app/controllers/vehicle_checkers_controller.rb
app/models/compliance.rb
app/models/vehicle_details.rb
app/views/vehicle_checkers/_taxi_or_phv_checkbox.html.haml
app/views/vehicle_checkers/country_input/_errored.html.haml
app/views/vehicle_checkers/country_input/_normal.html.haml
features/step_definitions/vehicle_checker_steps.rb
features/vehicle_checker.feature
spec/api_wrappers/compliance_checker_api/vehicle_compliance_spec.rb
spec/models/compliance_spec.rb
yarn.lock

[JIRA](https://eaflood.atlassian.net/browse/CAZB-316)

[WIP][VCCS-922] Add taxi or phv checkbox

---

Dockerfile.test
yarn.lock

[NT] Update ruby alpine version to fix ci failing

---

Dockerfile.build

[NT] Update ruby alpine version in Dockerfile.build

---

app/views/air_zones/compliance.html.haml

One outcome of GDS assessment was the need to update content on the Compliance page. This PR updates the page to remove the coloured panels and updates link text.
JIRA references:
* [CAZB-335](https://eaflood.atlassian.net/browse/CAZB-335)
* [CAZB-338](https://eaflood.atlassian.net/browse/CAZB-338)
Manual testing and inspection. See below.

compliance.html.haml: Remove panels and update link text.

---

app/views/air_zones/compliance.html.haml

[NT] Fix end to end tests

---

app/views/air_zones/compliance.html.haml

[JIRA](https://eaflood.atlassian.net/browse/CAZB-355)
New text added.
Also, i fixed a small bug with `br`, if you take are look to[ CAZB-335](https://eaflood.atlassian.net/browse/CAZB-335) there are no additional lines.
**BEFORE:**
--------------------------------------------------------------------------------
**AFTER:**

[CAZB-355] Update compliance page

---

.github/PULL_REQUEST_TEMPLATE

[NT] Update github pr template

---

.drone.yml

[NT] Update drone.yml (removed `exclude 961` from yarn audit)

---

app/views/air_zones/caz_selection.html.haml
app/views/air_zones/compliance.html.haml
app/views/vehicle_checkers/confirm_details.html.haml
app/views/vehicle_checkers/enter_details.html.haml
app/views/vehicle_checkers/incorrect_details.html.haml
app/views/welcome/index.html.haml
pa11y/.pa11yci.conf.js

[NT] Fix pa11y tests

---

pa11y/.pa11yci.conf.js

[NT] Update pa11y test

---

jmeter/manual-load-test/vccs-ve-concurrency-test.jmx
jmeter/valid_vehicle_compliance.jmx

jmeter fixes

---

Gemfile.lock
app/views/welcome/index.html.haml
package.json
yarn.lock

[JIRA](https://eaflood.atlassian.net/browse/CAZB-373)

[CAZB-373] Update welcome page content

---

app/views/accessibility/index.html.haml

[CAZB-293] Fix typo on accessibility page

---

.drone.yml
app/models/confirm_details_form.rb
app/views/accessibility/index.html.haml
app/views/air_zones/compliance.html.haml
config/locales/en.yml
features/vehicle_checker.feature
spec/models/confirm_details_form_spec.rb
spec/requests/vehicle_checker_controller/submit_confirm_details_spec.rb

[CAZB-341](https://eaflood.atlassian.net/browse/CAZB-341)
[CAZB-335](https://eaflood.atlassian.net/browse/CAZB-335)
[CAZB-293](https://eaflood.atlassian.net/browse/CAZB-293)

[CAZB-341, CAZB-335, CAZB-293] Update content

---

.drone.yml
app/models/confirm_details_form.rb
app/views/accessibility/index.html.haml
app/views/air_zones/compliance.html.haml
config/locales/en.yml
features/vehicle_checker.feature
spec/models/confirm_details_form_spec.rb
spec/requests/vehicle_checker_controller/submit_confirm_details_spec.rb

Merge in copy update into release v1.1.1

[CAZB-341, CAZB-335, CAZB-293] Update content (#312)

---

.env.example
config/environments/production.rb
config/initializers/content_security_policy.rb
yarn.lock

https://eaflood.atlassian.net/browse/CAZB-436

[CAZB-436] Add Cloudfront integration

---

app/controllers/vehicle_checkers_controller.rb
app/models/confirm_details_base_form.rb
app/models/confirm_details_form.rb
app/models/confirm_details_taxi_form.rb
app/views/vehicle_checkers/taxi_or_phv_input/_radio_buttons.html.haml
features/step_definitions/vehicle_checker_steps.rb
features/support/mock_helpers.rb
features/vehicle_checker.feature
spec/models/confirm_details_taxi_form_spec.rb

[JIRA](https://eaflood.atlassian.net/browse/CAZB-432)

[CAZB-432] Display taxi radio button only for non taxi vehicles

---

config/environments/production.rb

[NT] Add header

---

app/controllers/vehicle_checkers_controller.rb
app/models/confirm_details_base_form.rb
app/models/confirm_details_taxi_form.rb
app/views/vehicle_checkers/taxi_or_phv_input/_radio_buttons.html.haml
features/step_definitions/vehicle_checker_steps.rb
features/support/mock_helpers.rb
features/vehicle_checker.feature
spec/models/confirm_details_taxi_form_spec.rb

Promotes conditional appearance of the taxi radio button to the SIT environment,
JIRA ref: [CAZB-432](https://eaflood.atlassian.net/jira/software/projects/CAZB/boards/649?selectedIssue=CAZB-432)

candidate-release/promote-conditional-taxi-button-to-sit

---

app/controllers/vehicle_checkers_controller.rb
app/models/confirm_details_base_form.rb
app/models/confirm_details_taxi_form.rb
app/views/vehicle_checkers/taxi_or_phv_input/_radio_buttons.html.haml
features/step_definitions/vehicle_checker_steps.rb
features/support/mock_helpers.rb
features/vehicle_checker.feature
spec/models/confirm_details_taxi_form_spec.rb

Promote release/v1.1.1 to Pre-PROD

---

.drone.yml

Adds drone steps for deploying to new ST environment on creation of a release-candidate/* branch

Add drone steps for new ST environment

---

app/models/vehicle_details.rb
app/views/vehicle_checkers/taxi_or_phv_input/_radio_buttons.html.haml
features/step_definitions/helper_steps.rb
features/step_definitions/vehicle_checker_steps.rb
features/vehicle_checker.feature
spec/models/vehicle_details_spec.rb

[JIRA](https://eaflood.atlassian.net/browse/CAZB-451)

[CAZB-451] Hide taxi button for n1, n2, n3 and m3 vehicles types

---

.drone.yml

[NT] Add basic auth to pa11y tests

---

app/views/layouts/_header.html.haml
app/views/privacy_notice/index.html.haml
app/views/welcome/index.html.haml
features/privacy_notice.feature

[JIRA](https://eaflood.atlassian.net/browse/CAZB-435)

[CAZB-435] Update content

---

jmeter/valid_vehicle_compliance.jmx

fixed test

---

features/step_definitions/helper_steps.rb
features/step_definitions/vehicle_checker_steps.rb
features/vehicle_checker.feature
spec/models/vehicle_details_spec.rb

Promote Conditional taxi checkbox to ST

---

app/controllers/vehicle_checkers_controller.rb
app/models/confirm_details_base_form.rb
app/models/vehicle_details.rb
app/views/vehicle_checkers/confirm_details.html.haml
app/views/vehicle_checkers/taxi_or_phv_input/_radio_buttons.html.haml
features/step_definitions/helper_steps.rb
features/step_definitions/vehicle_checker_steps.rb
features/vehicle_checker.feature
pa11y/.pa11yci.conf.js
spec/models/confirm_details_form_spec.rb
spec/models/confirm_details_taxi_form_spec.rb
spec/models/vehicle_details_spec.rb
spec/requests/vehicle_checker_controller/submit_confirm_details_spec.rb

Promote conditional taxi box changes to SIT.

promote-conditional-taxi-box-to-SIT

---

.drone.yml

Ammended web addresses and browser stack set

---

app/views/air_zones/compliance.html.haml

[JIRA](https://eaflood.atlassian.net/browse/CAZB-499)

[CAZB-499] Update compliance page

---

app/views/air_zones/compliance.html.haml

[JIRA](https://eaflood.atlassian.net/browse/CAZB-499)

[CAZB-474] Update compliance page

---

app/views/contact_forms/index.html.haml

[JIRA](https://eaflood.atlassian.net/browse/CAZB-521)

[CAZB-521] Update contact form page

---

.drone.yml

[NT] Refactoring drone.yml

---

app/views/air_zones/compliance.html.haml

Missing commit from ST release means that the text currently appears in the wrong place.

[CAZB-474] Update compliance page (#348)

---

app/views/contact_forms/index.html.haml

[CAZB-521] Update contact form

---

app/views/cookies/_cookie_control.html.haml
app/views/cookies/index.html.haml

[JIRA](https://eaflood.atlassian.net/browse/CAZB-585)

[CAZB-585] Update cookies page

---

pa11y/.pa11yci.conf.js

[CAZB-614] Fix accessibility tests and zap tests

---

app/views/privacy_notice/index.html.haml

Text chage for privacy statement as per [CAZB-690](https://eaflood.atlassian.net/browse/CAZB-690)
N/A
Run locally. Manual inspection.

index.html.haml: Update privacy statement.

---

app/helpers/application_helper.rb
app/views/cookies/_cookie_control.html.haml
app/views/cookies/_ga.html.haml
app/views/cookies/_session.html.haml
app/views/cookies/index.html.haml
app/views/layouts/_cookie_control.html.erb
app/views/layouts/_header.html.haml
config/application.rb
spec/models/vehicle_details_spec.rb

[JIRA](https://eaflood.atlassian.net/browse/CAZB-454)

[CAZB-454] Content change to VCCS Cookie Policy

---

app/views/layouts/_cookie_control.html.erb

[JIRA](https://eaflood.atlassian.net/browse/CAZB-642)

[CAZB-454] `Accept all cookies` button enabled GA cookies by default

---

app/views/privacy_notice/index.html.haml

As per described under https://eaflood.atlassian.net/browse/CAZB-722

Update privacy notice to allow storage of VRNS for 30 days

---

app/views/layouts/_cookie_control.html.erb
yarn.lock

[JIRA](https://eaflood.atlassian.net/browse/CAZB-738)

[CAZB-738] Hide Control Cookie buttons and add `Save and close` button

---

app/views/layouts/_cookie_control.html.erb

[CAZB-738] Remove Control Cookie buttons from DOM

---

app/javascript/packs/application.js
app/javascript/src/cookieControl.js
app/views/layouts/_cookie_control.html.erb

[NT] Fix Cookie Control black button

---

config/application.rb
config/environments/production.rb
lib/custom_logger.rb

[CAZSM-8] Load custom logger in production

---

config/environments/production.rb

[CAZSM-8] Add debug log level to prod

---

config/environments/production.rb

[NT] Show custom logs in production

---

config/initializers/filter_parameter_logging.rb

Update logging fixes deployed previously to DEV to also remove param logging from contact form.
Additional param filters added
Run locally and tested with param logging.

[CAZSM-8 - ]Added extra param logging filters to account for contact form

---

.drone.yml

better build names

---

pa11y/.pa11yci.conf.js

change vrn

---

app/views/vehicle_checkers/enter_details.html.haml
app/views/vehicle_checkers/vrn_input/_errored.html.haml
app/views/vehicle_checkers/vrn_input/_normal.html.haml
features/step_definitions/path_expectations.rb
features/vehicle_checker.feature

https://eaflood.atlassian.net/browse/CAZB-723

[CAZB-723] Update enter details page

---

app/views/air_zones/caz_selection.html.haml
app/views/air_zones/compliance.html.haml
config/locales/en.yml

https://eaflood.atlassian.net/browse/CAZB-764
https://eaflood.atlassian.net/browse/CAZB-765
https://eaflood.atlassian.net/browse/CAZB-766
-------------
--------------

[CAZB-764, CAZB-765, CAZB-766] Update content

---

config/locales/en.yml
features/step_definitions/vehicle_checker_steps.rb
features/vehicle_checker.feature

https://eaflood.atlassian.net/browse/CAZB-765

[CAZB-765] Fix error message on enter details page

---

config/locales/en.yml
features/vehicle_checker.feature

[NT] Fix error message typo on the enter vrn page

---

.drone.yml

[NT] Ignore security warning for yarn audit

---

.drone.yml
config/locales/en.yml
features/vehicle_checker.feature

Deploy v1.7.3 to ST

---

app/api_wrapper/compliance_checker_api.rb
app/models/compliance.rb
app/models/compliance_details.rb
app/models/vehicle_details.rb
app/views/air_zones/compliance.html.haml
spec/fixtures/files/vehicle_compliance_response.json
spec/models/compliance_details_spec.rb

Updating the front end as per CAZB-646 to show specific text when a vehicle is compliant because of retrofit.

Feature/cazb 646/update exemption flow

---

.drone.yml

added link tests

---

app/javascript/styles/application.scss
app/views/vehicle_checkers/confirm_details.html.haml

https://eaflood.atlassian.net/browse/CAZB-27

[CAZB-27] Add table header to the vehicle details page

---

app/views/air_zones/compliance.html.haml
app/views/vehicle_checkers/cannot_determine.html.haml
app/views/welcome/index.html.haml

Feature/cazb 1058/update charge text

---

app/views/air_zones/_go_ultra_low_icon.html.haml
app/views/layouts/_footer.html.haml

Jira card: https://eaflood.atlassian.net/browse/CAZB-35
Fore Screen readers we need to set appropriate titles for image links.
Updated two links:

[CAZB-35] Fix Image Links titles

---

app/views/vehicle_checkers/confirm_details.html.haml

https://github.com/InformedSolutions/JAQU-CAZ-Vehicle-Compliance-Checker-Web/commit/59f399bf29270583ec3fd7ee630c6ae262e7ccfa
Also i fixed a bug, to resolve failed accessibility test
http://drone-185002984.eu-west-2.elb.amazonaws.com/InformedSolutions/JAQU-CAZ-Vehicle-Compliance-Checker-Web/1294/1/15

[CAZB-27] Update table header on the vehicle details page

---

.drone.yml
app/views/vehicle_checkers/incorrect_details.html.haml
features/step_definitions/vehicle_checker_steps.rb
features/vehicle_checker.feature

update content on incorrect details page

---

app/views/accessibility/index.html.haml
app/views/air_zones/_go_ultra_low_icon.html.haml
app/views/air_zones/caz_selection.html.haml
app/views/air_zones/compliance.html.haml
app/views/contact_forms/index.html.haml
app/views/cookies/_ga.html.haml
app/views/cookies/index.html.haml
app/views/layouts/_feedback_section.html.haml
app/views/privacy_notice/index.html.haml
app/views/vehicle_checkers/exemption.html.haml
app/views/vehicle_checkers/incorrect_details.html.haml
app/views/vehicle_checkers/non_uk.html.haml
app/views/vehicle_checkers/number_not_found.html.haml
app/views/welcome/index.html.haml

Jira card: https://eaflood.atlassian.net/browse/CAZB-33
Updated all external links in the app.
Reviewed all pages.
Screens added to comments in the Jira card.

[CAZB-33] Add text to open in new window links

---

app/api_wrapper/compliance_checker_api.rb
app/models/compliance.rb
app/models/compliance_details.rb
app/models/vehicle_details.rb
spec/fixtures/files/vehicle_compliance_response.json
spec/models/compliance_details_spec.rb

Jira card: https://eaflood.atlassian.net/browse/CAZB-1189
Removed no longer used URLs from the docs and tests.
N/A
N/A

[CAZB-1189] Removes urls from docs and tests

---

app/views/air_zones/compliance.html.haml
app/views/vehicle_checkers/cannot_determine.html.haml
app/views/welcome/index.html.haml

Update release v1.9.0

---

app/helpers/application_helper.rb
app/views/accessibility/index.html.haml
app/views/air_zones/compliance.html.haml
app/views/contact_forms/index.html.haml
app/views/cookies/_ga.html.haml
app/views/cookies/index.html.haml
app/views/layouts/_feedback_section.html.haml
app/views/privacy_notice/index.html.haml
app/views/vehicle_checkers/incorrect_details.html.haml
app/views/vehicle_checkers/non_uk.html.haml
app/views/vehicle_checkers/number_not_found.html.haml
app/views/welcome/index.html.haml

Jira card: https://eaflood.atlassian.net/browse/CAZB-33

[CAZB-33] Fixes opens in a new window links

---

app/views/air_zones/compliance.html.haml
pa11y/.pa11yci.conf.js

Fix Pa11y tests for new compliance design

---

.drone.yml

removed perf tests

---

app/views/air_zones/_go_ultra_low_icon.html.haml

Jira card: https://eaflood.atlassian.net/browse/CAZB-35
Link should open in the same card.

[CAZB-35] Fix Go Ultra Low Link

---

app/views/air_zones/compliance.html.haml
features/vehicle_checker.feature
yarn.lock

https://eaflood.atlassian.net/browse/CAZB-1286
* Updated compliance page content.
* Verified with WAVE

[CAZB-1286] Compliance page content update

---

app/models/vehicle_details.rb
features/air_zones.feature
features/step_definitions/vehicle_checker_steps.rb
features/vehicle_checker.feature
spec/fixtures/files/vehicle_details_response.json
spec/models/vehicle_details_spec.rb

https://eaflood.atlassian.net/browse/CAZB-475

[CAZB-475] Shows Taxi Radio button only for M1/M2 Vehicle Type Approvals

---

config/initializers/content_security_policy.rb

Add font src to csp config

---

app/controllers/application_controller.rb

Exclude basic auth for packs/media path

---

config/initializers/content_security_policy.rb

Temporary turn off the CSP

---

config/initializers/check_request_format.rb

Add woff format do `CheckRequestFormat`

---

.drone.yml
app/javascript/styles/cookie_control.scss
app/views/layouts/_cookie_control.html.erb
app/views/layouts/application.html.haml
package.json
yarn.lock

https://eaflood.atlassian.net/browse/CAZB-1029

[CAZB-1029] Update CookieControl to version 9

---

app/views/layouts/application.html.haml

Add 'text/javascript' type to Control Cookie script

---

.drone2.yml

sonar scan fix

---

config/application.rb

Fix for https://eaflood.atlassian.net/browse/CAZB-1325

[CAZB-1325] Contact Clean Air Zones link in the Start page is not accessible from IE 11

---

app/views/layouts/application.html.haml

https://eaflood.atlassian.net/browse/CAZB-1507

[CAZB-1512] Update check sum for Cookie Controller

---

Gemfile.lock
app/views/air_zones/compliance.html.haml
app/views/layouts/application.html.haml

Update ST with civic cookie controller hash removal

Update ST with civic cookie controller hash removal

---

app/controllers/vehicle_checkers_controller.rb
spec/requests/vehicle_checker_controller/confirm_details_spec.rb

https://eaflood.atlassian.net/browse/CAZB-1656
The idea is to revert changes introduced by the following PR: https://github.com/InformedSolutions/JAQU-CAZ-Vehicle-Compliance-Checker-Web/pull/436/files

[CAZB-1656] Restore operating on VRN provided by user

---

app/models/vehicle_details.rb

[CAZB-1656] Display VRN provided by user

---

app/views/air_zones/compliance.html.haml
features/vehicle_checker.feature

Minor copy adjustment on compliance page to remove refunds text.

[CAZB-1660] Minor copy adjustment on compliance page

---

.drone2.yml

updated secrets and account_name

---

.drone2.yml

Featues/cazb 1571/drone controlled st changes

---

app/javascript/styles/cookie_control.scss

[CAZ-2282] add cookie control focus css

---

.drone2.yml

Drone file corrections

---

.drone2.yml

updated drone steps for sit environment

---

.drone2.yml

Promote SIT drone fixes

---

.drone2.yml

updated preprod pipeline

---

.drone2.yml

Updated prod deployment steps

---

.drone2.yml

fixes the permissions

---

.drone2.yml

Updated docker image versions

---

.drone2.yml

updated drone file

---

.drone2.yml

Run prod pipeline for VCCS web layer in new AWS account

Run prod pipeline for VCCS web layer in new AWS account

---

.drone2.yml

Correct ECS rollout task in prod for new AWS account

Correct ECS rollout task in prod

---

.drone2.yml

Update new prod with corrected ECS task rollout

Update new prod with corrected ECS task rollout

---

app/models/compliance.rb

[CAZ-2842] Make CAZ listing alphabetical

---

.drone2.yml

Removed preprod, prod service account credential references

---

config/locales/en.yml
features/vehicle_checker.feature

https://eaflood.atlassian.net/browse/CAZB-1911

[CAZB-1911] Error message changes

---

.drone2.yml

Updated UAT drone steps

---

.drone2.yml

updated uat pipeline name

---

app/models/compliance.rb
app/models/vrn_form.rb
config/locales/en.yml
features/vehicle_checker.feature
spec/models/vrn_form_spec.rb

Update v1.12 with develop (selected commits)

---

app/views/accessibility/index.html.haml

https://eaflood.atlassian.net/browse/CAZB-2056

[CAZB-2056]  accessibility statement

---

.drone2.yml

drone2 file changes to develop branch

---

app/views/accessibility/index.html.haml

[CAZB-2056] Update gov pay link

---

app/views/accessibility/index.html.haml

Revert accessibility statement updates

---

.drone2.yml

updated prod pipeline

---

.drone2.yml
app/api_wrapper/compliance_checker_api.rb
app/controllers/air_zones_controller.rb
app/models/compliance.rb
app/models/non_uk_compliant_vehicle_details.rb
app/views/air_zones/compliance.html.haml
features/vehicle_checker.feature
spec/fixtures/files/non_chargeable_vehicle_compliance_response.json
spec/models/compliance_spec.rb
spec/models/non_uk_compliant_vehicle_details_spec.rb
spec/rails_helper.rb
spec/requests/air_zones/compliance_spec.rb
spec/requests/vehicle_checker_controller/confirm_details_spec.rb
spec/requests/vehicle_checker_controller/submit_confirm_details_spec.rb
spec/requests/vehicle_checker_controller/submit_details_spec.rb
spec/support/fixtures_helpers.rb

https://eaflood.atlassian.net/browse/CAZB-2385

[CAZB-2503][CAZB-2505][CAZB-2506] VC result page update

---

.drone2.yml

Cutover SIT domain for Release v1.11.0

Cutover SIT domain for Release v1.11.0

---

app/views/air_zones/compliance.html.haml

[CAZB-2505] Word change

---

app/views/vehicle_checkers/number_not_found.html.haml

Typo correction on vehicle not found page

[CAZB-2126] Typo correction on vehicle not found page

---

.drone.yml
.drone2.yml

https://eaflood.atlassian.net/browse/CAZB-2659
Updated env variable.

[CAZB-2659] Survey Link Update - Qualtrics (Production)

---

.drone2.yml
app/views/vehicle_checkers/confirm_details.html.haml

* https://eaflood.atlassian.net/browse/CAZB-2598

[CAZB-2598] Change heading to table header

---

app/views/vehicle_checkers/vrn_input/_errored.html.haml
app/views/vehicle_checkers/vrn_input/_normal.html.haml

https://eaflood.atlassian.net/browse/CAZB-2596
* Updated hint text markup

[CAZB-2596] Updated hint styling

---

.drone2.yml
app/views/vehicle_checkers/confirm_details.html.haml
app/views/vehicle_checkers/vrn_input/_errored.html.haml
app/views/vehicle_checkers/vrn_input/_normal.html.haml

Update ST with latest develop content

Update ST with latest develop content

---

app/views/vehicle_checkers/confirm_details.html.haml

Change casing to sentence case for Vehicle Details page

[CAZB-2598] Change casing to sentence case for Vehicle Details

---

app/views/vehicle_checkers/vrn_input/_errored.html.haml
app/views/vehicle_checkers/vrn_input/_normal.html.haml

Update ST with fix for CAZB-2598

Update ST with fix for CAZB-2598

---

app/views/vehicle_checkers/incorrect_details.html.haml

https://eaflood.atlassian.net/browse/CAZB-2801

[CAZB-2801] Incorrect details wording change

---

.drone2.yml

changed variable

---

.drone2.yml
app/views/vehicle_checkers/incorrect_details.html.haml

Update RC with Develop

---

app/api_wrapper/compliance_checker_api.rb
app/controllers/air_zones_controller.rb
app/models/compliance.rb
app/views/air_zones/compliance.html.haml
spec/api_wrappers/compliance_checker_api/vehicle_compliance_spec.rb
spec/fixtures/files/phgv_discount_not_available_vehicle_compliance_response.json
spec/fixtures/files/vehicle_compliance_response.json
spec/models/compliance_spec.rb

https://eaflood.atlassian.net/browse/CAZB-2831
Add link which inform about possible discount for PHGV in Bath CAZ.
Manually, test updated

[CAZB-2831] VCCS UI - Add conditional discount notice for PHGV Bath

---

app/models/compliance_details.rb
app/models/non_uk_compliant_vehicle_details.rb
app/views/air_zones/compliance.html.haml

https://eaflood.atlassian.net/browse/CAZB-2648
Fix sorting in numeric value column
Manually, test fixed

[CAZB-2648] Fix 'Clean Air Zone Charge' table sort by 'Daily Charge'

---

.drone2.yml

fixed passwords

---

.drone2.yml

Adds AWS Cli to terraform runs to rc/v1.13.1

---

app/views/air_zones/compliance.html.haml
app/views/welcome/index.html.haml

Change was requested by Michael Power on Slack channel.

Remove full stop from CAZ link

---

app/views/air_zones/compliance.html.haml

[CAZB-3356] Update how we calculate your charge content

---

app/javascript/styles/application.scss

https://eaflood.atlassian.net/browse/CAZB-3450
`display: block;` will only be applied to `.back-link` on printed version of the page
Manually
---

[CAZB-3450] Back links style adjustment

---

app/views/air_zones/compliance.html.haml

Promote VCCS v1.14.2 to Pre-Production

Promote VCCS v1.14.2 to Pre-Production

---

app/views/vehicle_checkers/number_not_found.html.haml

https://eaflood.atlassian.net/browse/CAZB-3341

[CAZB-3341] Vehicle not found page content fixes

---

.gitignore
Gemfile
Gemfile.lock
app/api_wrapper/base_api.rb
config/locales/en.yml
spec/api_wrappers/compliance_checker_api/vehicle_compliance_spec.rb
spec/i18n_spec.rb
spec/spec_helper.rb
spec/support/shared_examples/invalid_country_input.rb
spec/support/shared_examples/invalid_vrn_input.rb

Removed unused keys and added test. Also sorted keys by i18n-tasks normalize command, needed for test passing.

Add `i18n-tasks` gem

---

yarn.lock

Bump libs to update expose-loader version

---

app/views/static_pages/privacy_notice.html.haml
features/privacy_notice.feature

https://eaflood.atlassian.net/browse/CAZB-3529

[CAZB-3529] Content update on the Privacy policy page

---

app/views/static_pages/privacy_notice.html.haml
features/privacy_notice.feature

https://eaflood.atlassian.net/browse/CAZB-3529

[CAZB-3632] Update title on Privacy Notice page

---

app/views/vehicle_checkers/confirm_uk_details.html.haml
features/step_definitions/vehicle_checker_steps.rb
features/vehicle_checker.feature

https://eaflood.atlassian.net/browse/CAZB-3881

[CAZB-3881] Fraud prevention – Fix validation flow for uk registred page

---

app/views/static_pages/privacy_notice.html.haml

* Link to JIRA Card: https://eaflood.atlassian.net/browse/CAZB-3994
* Added section on the Privacy Notice page
N/A

[CAZB-3994] Added ENLs to Privacy Notice

---

app/views/static_pages/privacy_notice.html.haml

[CAZB-3994] Removed dot and semicolon from Privacy Notice

---

app/controllers/vehicle_checkers_controller.rb
app/views/air_zones/compliance.html.haml
features/vehicle_checker.feature
spec/models/confirm_details_form_spec.rb
spec/models/confirm_details_taxi_form_spec.rb
spec/requests/vehicle_checker_controller/submit_details_spec.rb

https://eaflood.atlassian.net/browse/CAZB-3881

[CAZB-3881] Fix back button flow on compliance page

---

app/controllers/vehicle_checkers_controller.rb
app/views/air_zones/compliance.html.haml
app/views/static_pages/privacy_notice.html.haml
app/views/vehicle_checkers/incorrect_details.html.haml
features/vehicle_checker.feature
spec/models/confirm_details_form_spec.rb
spec/models/confirm_details_taxi_form_spec.rb
spec/requests/vehicle_checker_controller/submit_details_spec.rb

Update RC with draft

---

app/views/static_pages/privacy_notice.html.haml

Promote VCCS v1.17.3 to Pre-Prod

Promote VCCS v1.17.3 to Pre-Prod

---

.drone2.yml

 [CAZB-4063] Migrate pipeline to Terraform v0.12.23 

---

.drone2.yml

Promote release v1.17.4 to pre-production

Promote release v1.17.4 to pre-production

---

.drone2.yml
app/views/static_pages/privacy_notice.html.haml

Promote VCCS v1.17.4 to Production

Promote VCCS v1.17.4 to Production

---

.rubocop.yml
Gemfile.lock
app/views/air_zones/compliance.html.haml
package.json
spec/models/confirm_details_form_spec.rb
spec/models/vrn_form_spec.rb
spec/requests/vehicle_checker_controller/submit_details_spec.rb
spec/spec_helper.rb
yarn.lock

https://eaflood.atlassian.net/browse/CAZB-4055

[CAZB-4055] Amend data message in results page

---

app/javascript/packs/application.js
app/javascript/src/backLink.js
app/views/common/_js_back_link.html.haml
app/views/vehicle_checkers/enter_details.html.haml

https://eaflood.atlassian.net/browse/CAZB-4097

[CAZB-4097] Update back button to JS on enter details page

---

app/models/compliance_details_base.rb
app/views/air_zones/compliance.html.haml
config/application.rb
spec/models/compliance_details_base_spec.rb

https://eaflood.atlassian.net/browse/CAZB-4022

[CAZB-3953] Update results page to include link to payments

---

app/views/vehicle_checkers/non_uk.html.haml

https://eaflood.atlassian.net/browse/CAZB-2875

[CAZB-2875] Change `drive` to `drove` on non-uk page

---

app/views/air_zones/compliance.html.haml

* Link to JIRA Card: https://eaflood.atlassian.net/browse/CAZB-3856

[CAZB-3856] How we calculate your charge update

---

app/models/compliance_details_base.rb
features/air_zones.feature
spec/models/compliance_details_base_spec.rb

https://eaflood.atlassian.net/browse/CAZB-3953?focusedCommentId=276097

[CAZB-3953] Update results page to include dynamic links

---

jmeter/manual-load-test/vccs-concurrency-test.jmx
jmeter/valid_vehicle_compliance.jmx

removed taxi chkbox

---

pa11y/.pa11yci.conf.js

http://drone-1587293244.eu-west-2.elb.amazonaws.com/InformedSolutions/JAQU-CAZ-Vehicle-Compliance-Checker-Web/793/1/14

[CAZB-4123] Fix accessibility test

---

app/views/static_pages/privacy_notice.html.haml

* Link to JIRA: https://eaflood.atlassian.net/browse/CAZB-4143
* Privacy Notice copy updated.

[CAZB-4143] Privacy Notice update

---

app/views/air_zones/compliance.html.haml

Jira Card: https://eaflood.atlassian.net/browse/CAZB-4258

[CAZB-4258] Amend VCCS results screen for motorhomes/PHGV

---

app/views/air_zones/compliance.html.haml

Promote VCCS v2.0.1 to Pre-Prod

Promote VCCS v2.0.1 to Pre-Prod

---

app/views/static_pages/accessibility_statement.html.haml

https://eaflood.atlassian.net/browse/CAZB-2084

[CAZB-2084] Update accessibility policy content

---

app/views/static_pages/privacy_notice.html.haml

Jira Card: https://eaflood.atlassian.net/browse/CAZB-4387

[CAZB-4387] Combine and update Privacy Notice

---

app/views/static_pages/accessibility_statement.html.haml

Jira Card: https://eaflood.atlassian.net/browse/CAZB-4389

[CAZB-4389] Update Accessibility Statement

---

.rubocop.yml
app/controllers/application_controller.rb
app/controllers/vehicle_checkers_controller.rb
app/models/vrn_form.rb

Can't reproduce it locally, but found the same problem in Fleets UI - [link](https://eaflood.atlassian.net/browse/CAZB-3002)

[CAZB-3002] Disable cache on enter details page

---

app/views/static_pages/privacy_notice.html.haml

[CAZB-4461] - VCCS UI - Privacy Notice amendments - in line with Customer Contact Centre

---

app/controllers/vehicle_checkers_controller.rb
app/models/vrn_form.rb

https://eaflood.atlassian.net/browse/CAZB-4239
I removed the unnecessary method, because inside vrn form we're doing the same removing spaces and tabs.

[CAZB-4239] Refactor validating vrn to be consistent with payments ui

---

app/controllers/vehicle_checkers_controller.rb

[CAZB-4296] Fix leading zeros for exempt vehicles

---

app/controllers/vehicle_checkers_controller.rb
app/models/vrn_form.rb
app/views/static_pages/privacy_notice.html.haml
spec/models/vrn_form_spec.rb

Update draft with develop

---

app/controllers/vehicle_checkers_controller.rb
app/models/vehicle_details.rb

[CAZB-4296] fix leading zeros

---

app/views/air_zones/compliance.html.haml
yarn.lock

https://eaflood.atlassian.net/browse/CAZB-4640

[CAZB-4640] Add additional content to data message in VCCS results page

---

app/views/air_zones/compliance.html.haml

https://eaflood.atlassian.net/browse/CAZB-4640

[CAZB-4640] Update content to data message in VCCS results page

---

app/controllers/application_controller.rb
app/services/security/host_header_validator.rb
spec/services/security/host_header_validator_spec.rb

[CAZB-4855] Allow multiple hosts

---

app/views/static_pages/privacy_notice.html.haml

https://eaflood.atlassian.net/browse/CAZB-4834

[CAZB-4834] Privacy notice amendments

---

.drone2.yml

http://drone-1587293244.eu-west-2.elb.amazonaws.com/InformedSolutions/JAQU-CAZ-Vehicle-Compliance-Checker-Web/1076/1/13
Fix for `The config file "/drone/src/pa11y/.pa11yci.conf" could not be loaded`

Fix accessibility tests

---

.dockerignore
.drone2.yml

Fix zap tests

---

.dockerignore

Update docker ignore file to fix no space left on device

---

app/views/static_pages/privacy_notice.html.haml

Update release candidate/v2.4.0

Update release candidate/v2.4.0

---

app/views/layouts/_gtm_script.html.erb
config/initializers/content_security_policy.rb

[CAZB-4899] Update "unsafe-inline" CSP policy to use nonces

---

app/views/layouts/_cookie_control.html.erb
app/views/layouts/_gtm_script.html.erb
app/views/layouts/application.html.haml
config/initializers/content_security_policy.rb

Use value as true and small refactoring to easy edit the list of hashes.

[CAZB-4899] Refactor "unsafe-inline" CSP policy to use nonces

---

app/api_wrapper/base_api.rb
app/api_wrapper/compliance_checker_api.rb

[CAZB-4190] Update Base API to handle well non-ascii URIs

---

Gemfile
Gemfile.lock
app/api_wrapper/base_api.rb
config/application.rb
sonar-project.properties

Add ruby lib to fix loading gem in production mode.
https://www.rubydoc.info/gems/addressable/Addressable/URI

[CAZB-4190] Add `addressable` gem to Gemfile to load in production

---

app/models/vehicle_details.rb
features/step_definitions/helper_steps.rb
features/step_definitions/vehicle_checker_steps.rb
features/support/mock_helpers.rb
features/vehicle_checker.feature
spec/models/vehicle_details_spec.rb
spec/requests/vehicle_checker_controller/confirm_details_spec.rb
spec/requests/vehicle_checker_controller/confirm_uk_details_spec.rb
spec/requests/vehicle_checker_controller/submit_confirm_details_spec.rb
spec/requests/vehicle_checker_controller/submit_confirm_uk_details_spec.rb
yarn.lock

* https://eaflood.atlassian.net/browse/CAZB-4278

[CAZB-4278] Update compliance check for undetermined vehicles

---

app/assets/stylesheets/no-javascript.css
app/views/common/_js_back_link.html.haml

https://eaflood.atlassian.net/browse/CAZB-4899

[CAZB-4899] Fix console error on enter details page

---

app/views/vehicle_checkers/non_uk.html.haml

Jiar Card: https://eaflood.atlassian.net/browse/CAZB-5041

[CAZB-5041] Add link to payments to non-uk page

---

.drone2.yml

[CAZB-4710] SIT and pre-prod domain migration

[CAZB-4710] SIT and pre-prod domain migration

---

app/views/vehicle_checkers/non_uk.html.haml

Jira Card: https://eaflood.atlassian.net/browse/CAZB-5041
Fixed wrong text update to link

[CAZB-5041] Fix Add link to payments to non-uk page

---

app/views/vehicle_checkers/non_uk.html.haml

[CAZB-5041] Fix Add link to payments to non-uk page (#791)

---

.drone2.yml

[CAZB-5004] Fix SIT2 codedeploy pointer

---

app/controllers/application_controller.rb
spec/requests/static_pages_controller_spec.rb

Jira Card: https://eaflood.atlassian.net/browse/CAZB-5107

[CAZB-5107] Update service to flag Invalid Host Headers with 403 error

---

app/controllers/application_controller.rb
app/views/vehicle_checkers/non_uk.html.haml
spec/requests/static_pages_controller_spec.rb

Draft release candidate/v2.5.0

---

Gemfile.lock
app/views/vehicle_checkers/cannot_determine.html.haml
app/views/vehicle_checkers/incorrect_details.html.haml
app/views/vehicle_checkers/number_not_found.html.haml

* https://eaflood.atlassian.net/browse/CAZB-5048
* https://eaflood.atlassian.net/browse/CAZB-5051
* https://eaflood.atlassian.net/browse/CAZB-5090

[CAZB-5048] DVLA content changes
