InformedSolutions/JAQU-CAZ-Vehicle-Compliance-Checker-Web

.drone.yml
Update drone step for ECS prod rollout to pull task definition from pre-prod rather than SIT (as pre-prod sits one down from prod in the pipeline).
=> Update ECS prod rollout step to draw from preprod

Gemfile.lock, app/views/layouts/_cookies_banner.haml
[CAZB-28](https://eaflood.atlassian.net/browse/CAZB-28)
[CAZB-31](https://eaflood.atlassian.net/browse/CAZB-31)
Now `'Accept cookies'` button receive keyboard focus first and can be clickable by keyboard.
=> [CAZB-28, CAZB-31] Update cookies banner to allow use keyboard focus

app/views/air_zones/caz_selection.html.haml, app/views/air_zones/compliance.html.haml, app/views/contact_forms/index.html.haml, app/views/contact_forms/result.html.haml, app/views/cookies/index.html.haml, app/views/errors/internal_server_error.html.haml, app/views/errors/not_found.html.haml, app/views/errors/service_unavailable.html.haml, app/views/vehicle_checkers/cannot_determine.html.haml, app/views/vehicle_checkers/confirm_details.html.haml, app/views/vehicle_checkers/enter_details.html.haml, app/views/vehicle_checkers/exemption.html.haml, app/views/vehicle_checkers/incorrect_details.html.haml, app/views/vehicle_checkers/non_uk.html.haml, app/views/vehicle_checkers/number_not_found.html.haml, app/views/welcome/index.html.haml, features/step_definitions/vehicle_checker_steps.rb, features/vehicle_checker.feature
On outcome of the Accessibility Audit was an observation that the page titles do not match the `<h1>` content of the page. This PR addresses that. 
JIRA ref:  [CAZB-340](https://eaflood.atlassian.net/browse/CAZB-340)
Manual inspection.
=> [CAZB-340] Update page titles

app/controllers/vehicle_checkers_controller.rb
POSTing without parameters to `/vehicle_checkers/enter_details` causes a 500 error. This is triggering alarms.
https://eaflood.atlassian.net/browse/CAZSM-1
If VRN is not provided default to an empty string. Then the vrn is not nil and validation is correctly handled without encountering an error/exception.
Other than manual testing, I have not tested this change. I am working under the assumption that the drone tests will cover this minor change.
=> If no VRN param passed, handle don't 500

app/controllers/vehicle_checkers_controller.rb
Reverts InformedSolutions/JAQU-CAZ-Vehicle-Compliance-Checker-Web#344
This is to understand, in develop, if these changes have affected the freshping monitoring. We have created an alarm to watch the DEV env and see if this revert handles current errors.
=> Revert "If no VRN param passed, handle don't 500"

config/application.rb, config/environments/production.rb, config/log_format.rb, yarn.lock
[CAZSM-8 - VCCS Web: Removal of VRM and IP PII from application logs (PRISM 14386)](https://eaflood.atlassian.net/browse/CAZSM-8)
Removal of Personally Identifiable Information from the VCCS ECS logs:
- VRMs
- IP Addresses
- Contact form details
A custom log formatter has been created that filters log messages, replacing strings that match IPV4 Regex with [REDACTED]. This formatter is used as part of the default logger. Other changes include the removal of verbose log_action calls to remove PII. IP Addresses were also removed from production log tagging.
Full test suite was run in local environment. 
Changes to the logs were reviewed manually, using actions that previously logged PII. Instances of IP addresses are replaced with [REDACTED] and VRM parameters in service calls are replaced …
=> Fix/cazsm 8/removal of ip addresses from application logs

Gemfile, Gemfile.lock, app/api_wrapper/compliance_checker_api.rb, app/services/sqs/base_message.rb, config/application.rb, config/environments/production.rb, config/initializers/filter_parameter_logging.rb, yarn.lock
[CAZSM-8 - VCCS Web: Removal of VRM and IP PII from application logs (PRISM 14386)](https://eaflood.atlassian.net/browse/CAZSM-8)
Removal of Personally Identifiable Information from the VCCS ECS logs:
- VRMs
- IP Addresses
- Contact form details
A custom log formatter has been created that filters log messages, replacing strings that match IPV4 Regex with [REDACTED]. This formatter is used as part of the default logger. Other changes include the removal of verbose log_action calls to remove PII. IP Addresses were also removed from production log tagging.
Full test suite was run in local environment. 
Changes to the logs were reviewed manually, using actions that previously logged PII. Instances of IP addresses are replaced with [REDACTED] and VRM parameters in service calls are replaced …
=> [CAZSM-8] Removal of ip addresses from application logs

.drone.yml
Drone file switched to use of echo -e command to correctly source github ssh key.
=> Fix for git ssh keys

app/helpers/application_helper.rb
Jira card:
https://eaflood.atlassian.net/browse/CAZB-36
Updated area-label to be aria-label
=> [CAZB-36] Fix typo in external_link_to helper method

app/controllers/application_controller.rb, config/initializers/check_request_format.rb, config/initializers/content_security_policy.rb, config/webpack/environment.js
Issue appears because VCCS was the first rails application which generates `config/webpack/environment.js` file without 
```
const fileLoader = environment.loaders.get('file').use.find(el => el.loader === 'file-loader');
fileLoader.options = myFileOptions;
```
without it fonts and logo paths generates with hash in path, for example
```
https://dev.cleanairzonevehiclecheck.co.uk/packs/media/fonts/bold-b542beb274-v2.woff2
---------
https://dev.cleanairzonevehiclecheck.co.uk/packs/media/fonts/bold-b542beb274-v2-616e5f21.woff2
```
=> Fix loading fonts

app/views/air_zones/compliance.html.haml
Correct Leeds CAZ tariff in compliance page. This should read B not C.
=> Correct Leeds CAZ tariff in compliance page

app/models/vrn_form.rb, spec/models/vrn_form_spec.rb
JIRA Card: https://eaflood.atlassian.net/browse/CAZB-1659
* When provided VRN begins with `0` and is marked as the UK, the validation is going to fail due to the wrong format.
* There are possible 2-characters formats like `9A`. Considering the card requirements it should be possible now to pass a single character VRNs for cases like `0G` but after consultation, it was decided that minimal length of VRN should remain 2.
* Updated specs.
* Manually.
=> [CAZB-1659] Consider VRNs with leading 0s as invalid for UK

app/api_wrapper/compliance_checker_api.rb, app/models/non_uk_compliant_vehicle_details.rb, spec/api_wrappers/compliance_checker_api/clean_air_zones_spec.rb, spec/fixtures/files/caz_list_response.json, spec/models/non_uk_compliant_vehicle_details_spec.rb
Link to JIRA Card: https://eaflood.atlassian.net/browse/CAZB-1971
* Removed hardcoded URLs to main info pages
* Added `mainInfoUrl` data from API response
* Manually
N/A
=> [CAZB-1971] Added mainInfoUrl to API response

.drone2.yml, app/helpers/application_helper.rb, app/javascript/styles/application.scss, app/views/air_zones/compliance.html.haml, app/views/static_pages/accessibility_statement.html.haml, app/views/static_pages/cookies.html.haml, app/views/static_pages/privacy_notice.html.haml, app/views/vehicle_checkers/cannot_determine.html.haml, app/views/vehicle_checkers/confirm_details.html.haml, app/views/vehicle_checkers/enter_details.html.haml, app/views/vehicle_checkers/exemption.html.haml, app/views/vehicle_checkers/incorrect_details.html.haml, app/views/vehicle_checkers/non_uk.html.haml, app/views/vehicle_checkers/number_not_found.html.haml
https://eaflood.atlassian.net/browse/CAZB-3323
Added `back_link` helper with css property `display: block`
=> [CAZB-3323] Fix Back link layout on printed Compliance page

app/views/vehicle_checkers/incorrect_details.html.haml, features/vehicle_checker.feature
https://eaflood.atlassian.net/browse/CAZB-3881
=> [CAZB-3881] Fix back button flow on incorrect vehicle details page

package.json, yarn.lock
Revert `expose-loader` bump version because of breaking changes with building jquery package.
http://drone-1587293244.eu-west-2.elb.amazonaws.com/InformedSolutions/JAQU-CAZ-Vehicle-Compliance-Checker-Web/716
=> [CAZB-4082] Fix deploy

app/views/welcome/index.html.haml, spec/fixtures/files/caz_list_response.json, spec/fixtures/files/vehicle_compliance_response.json, spec/models/compliance_details_base_spec.rb
[CAZB-3390](https://eaflood.atlassian.net/browse/CAZB-3390)
Leeds removed from the un-used starter page and replaced it with future CAZ in tests.
Executed rspec/cucumber tests against service.
=> [CAZB-3390] Remove Leeds references from the VCCS UI

.drone2.yml
Improves build speed and allows for docker image caching when pushing to ECR repository. This serves 2 benefits - one in that builds are 3 minutes faster to deploy; second - this reduces the number of pulls issued to Dockerhub (so reduces chance of hitting rate limits).
=> [NON-JIRA] Improve build speed in dev

Gemfile.lock
Author of mimemagic gem has decided to change license from MIT to GPL2
and  remove all older versions in the process. Unfortunately this gem is
a dependency of Rails. 
This change broke our CI builds:
http://drone-1587293244.eu-west-2.elb.amazonaws.com/InformedSolutions/JAQU-CAZ-Vehicle-Compliance-Checker-Web/890
We need to update it to the closes version available.
Old version of mimemagic has been removed https://github.com/rails/rails/issues/41750
This commit bumps the version up to the closest version available.
The only change introduced in 0.3.6 is license change (from MIT to GPL2)
In order to resolve the issue in other repos, one needs to run `bundle update mimemagic`,
(which should update it to 0.3.6) and ensure only mimemagic change has been commited
=> Update mimemagic to 0.3.6

Dockerfile.build, Dockerfile.test, Gemfile.lock
Recently there was a lot of drama around mimemagic gem - at first
mimemagic updated its licence to GPL2 to comply with its dependency
(freedesktop.org.xml) licence. In the process they yanked all
<0.3.6 licences and broke many builds (including ours) as 0.3.4
was direct dependency of Rails.
We have updated our Gemfile.lock to 0.3.6 to get our builds back
to green. This was yesterday. As of Today it looks like mimemagic
changed the owner. New owner extracted freedesktop.org.xml to be an outside
dependency, restored previous MIT licence, and again yanked all versions
<0.3.9 which again broke our build.
This commit bumps version to the closest available. We sincerely hope
we will not have to bump it again tomorrow.
If your build fails, please look at …
=> Fix build process by bumping mimemagic to 0.3.9

app/models/caz_link_display_data.rb, app/views/static_pages/privacy_notice.html.haml
https://eaflood.atlassian.net/browse/CAZB-4715
=> [CAZB-4715] Use operator name on privacy notice page

.iyarc, app/views/air_zones/compliance.html.haml, features/vehicle_checker.feature
https://eaflood.atlassian.net/browse/CAZB-4876
=> [CAZB-4876] Add js back button to compliance page
